FROM python:3.11-slim
WORKDIR /app

# recuired libraries 
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# copy and setup dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy all codes
COPY . .